Divsum pm
Piotr-Dev/Spoj1Divisor-Summation pull request #1
Opened 2017-01-05 09:26 UTC by MajewskiP

+code review request

2017-01-05 10:21 UTC, Piotr-Dev requested changes
Wymagane są poprawki

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                Console.WriteLine("Input:");
"Upiększanie" inputu nie jest konieczne w tym wypadku

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                Console.WriteLine(" \nOutput:");
"Upiększanie" outputu również nie jest konieczne w tym wypadku

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            {
zamiast int i `List<int>` w deklaracji można by uzyć var tym sposobem nazwy zmiennych łatwiej się czyta, a typ można wywnioskować lub użyć IDE

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            List<int> divisors = new List<int>();
tutaj tez można użyć 'var' ponieważ typ mamy już po prawej

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                if ((number % i) == 0) divisors.Add(i);
(number % i) == 0 można wyciagnąc do zmiennej np 'isDivisor'
'i' można by nazwać 'potentialDivisor'  -> poprawi to czytelnośc "divisors.Add(i);"

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        {
W metodzie:
typy zmiennych można zmienić na 'var'
Wyciągnąć walidację do oddzielnej metody, która będzie zawierała exception'y

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                var reader = new StringReader(NumberInput());
Chciałbym żeby  reader przyjmował "Console.OpenStandardInput()", a jeśli potrzebujesz operować na konsoli, to operuj na zmiennej 'reader'

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            const int minInputCount = 1;
To powinno znaleźć się w metodzie walidującej

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            var inputNumbers = new StringBuilder();
tutaj dublujesz to co robi zmienna reader, warto by jej użyć

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        public static string NumberInput()
Ta metoda wygląda jak jakiś HACK :) - warto przemyśleć jej implementację

2017-01-05 10:21 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        private static bool IsValidInputNumber(int inputNumber)
tutaj tez powinien się znaleźć odpowiedni Exception

2017-01-05 10:57 UTC, MajewskiP commented on Spoj1Divisor Summation/Program.cs
> +        public static string NumberInput()
a może by tak konkretnie coś?

2017-01-05 10:59 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        public static string NumberInput()
Konkrety poniżej :)

2017-01-05 11:00 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        public static string NumberInput()
Dodatkowo komentarz w miejsu wykorzystania metody. 

"Chciałbym żeby reader przyjmował "Console.OpenStandardInput()", a jeśli potrzebujesz operować na konsoli, to operuj na zmiennej 'reader'"

2017-01-09 00:01 UTC, Piotr-Dev requested changes
Jeszcze małe poprawki

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            DivisorSumationCalculation(inputCount,reader,writer);
Te metoda nie tylko oblicza sumy ale tez je wyświetla, spróbuj rozdzielić te zadania do oddzielnych metod

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            if (inputNumber < lowerLimit) throw new Exception("Incorrect input (must be greather than 1)");
można by tu użyć placeholderów w stringu na przykład : $("Incorrect input (must be greather than {lowerLimit})"

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                writer.WriteLine(CalculateDivisors(number).Sum());
Zapisywanie lepiej oddzielić od obliczeń, szczególnie że nazwa metody nie wskazuje na takie działanie

2017-01-09 09:05 UTC, merged