Tomek - Divisor Sumation
Piotr-Dev/Spoj1Divisor-Summation pull request #2
Opened 2017-01-05 09:36 UTC by tkomoszeski

Ready for code review.

2017-01-05 10:44 UTC, Piotr-Dev requested changes
Wymagane poprawki

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        public const int MinRange = 1;
Pomysł bardzo dobry, ale w tym wypadku const może być prywatny :)

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            WriteInformationAboutData("Input");
Upiekrzanie inputu nie jest konieczne

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            ValidateAndCountDivisorSumationFromInputNumbers(reader, writer);
Nazwa zawiera "and" co od razu wskazuje na to że metoda robi za dużo na raz

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            WriteInformationAboutData("Output");
Upiekrzanie outputu nie jest konieczne

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            bool isNumber = false;
Można by stworzyć oddzielna metodę walidującą dane

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                int amountOfInputs = 0;
zamiast int i string można użyć var poprawia to czytelność bo zmienne są pod sobą a typ można wywnioskować lub użyć IDE

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +            } while (!isNumber);
mozna by wykorzystać tutaj tutaj zmienna która określa ilość danych na wejściu

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                if (number < MinRange || number > MaxRange) continue;
zamiast 'continue' można by rzucić exception ponieważ w dokumentacji nie określono co w wypadku przekroczenia zakresu

2017-01-05 10:44 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                if (number % divider == 0)
number % divider == 0 można by wyciągnąć do zmiennej np 'isDivisable' albo 'isDivider'

2017-01-05 11:13 UTC, Ziumper commented on Spoj1Divisor Summation/Program.cs
> +                if (number < MinRange || number > MaxRange) continue;
W tym przypadku sprawę załatwia metoda TryParse()

2017-01-05 11:43 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                if (number < MinRange || number > MaxRange) continue;
TryParse połyka Exception :(
dodatkowo dostajesz 0 na outpucie
MSDN:
https://msdn.microsoft.com/en-us/library/f02979c7(v=vs.110).aspx

2017-01-05 11:53 UTC, Ziumper commented on Spoj1Divisor Summation/Program.cs
> +                if (number < MinRange || number > MaxRange) continue;
Tak, i potem resztą zajmuje się mój warunek  ` if (number < MinRange || number > MaxRange) continue;`

2017-01-09 00:01 UTC, Piotr-Dev requested changes
Jeszcze małe poprawki

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +                if (number < MinRange || number > MaxRange) continue;
Da się to uprościć :) 
Chodzi o to żeby ktoś nie musiał wnikać w to co zwraca TryParse w wypadku płędnego wyniku. Nie zawsze się pamięta te niuanse, dlatego powinniśmy unikać rozwiązań wymagających takiej "wiedzy tajemnej". Dodatkowo ktoś kto przyjdzie po tobie może być mniej doświadczony i to na pewno wsadzi go na "minę" w trakcie czytania kodu.

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +           var firstInputNumber = TakeDataFromInput(textFromInput);
dobrze by wskazać nazwą zmiennej czym jest pierwsza linia inputu żeby było jasne dlaczego traktujemy ją inaczej np inputCount albo inputAmmount.

Dodatkowo nazw metody TakeDataFromInput jest trochę zbyt ogólna a jej sygnatura wskazuje na bardziej okreslone działanie. Może np.: GetNumberFromInputString

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +           CalculateSumsDivisorForNumbers(firstInputNumber, reader, writer);
Dobrze by oddzielić obliczanie od wyświetlania danych

2017-01-09 00:01 UTC, Piotr-Dev commented on Spoj1Divisor Summation/Program.cs
> +        private static bool ValidateDataFromInput(int number)
te metoda nie musi zwraca bool'a ponieważ typ zwracany nie jest wykorzystywany nigdzie

2020-12-05 22:45 UTC, closed without merging